# Generated by Django 5.2.7 on 2025-11-02 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='postcode',
            new_name='postal_code',
        ),
    ]
